### ISSUE TITLE
Dicas e sugestões no código

### ISSUE THREAD

**Issue by arthurs159** [BernardoZacaron/Motorbike-Showcase#1]
Ei Bernardo, tem algumas sugestões que seria legal você adicionar no seu projeto, algumas mudanças no código também, vou deixar aqui em baixo:

![image](https://user-images.githubusercontent.com/77133022/216459019-71f71ff2-5579-4f45-8034-f5714ec16cb8.png)
Nessa parte, eu adicionaria um DTO, recebendo ele nos parâmetros e depois convertendo para a entidade, acho que assim ficaria bem melhor pois você não vai expor a sua entidade, você passa ela pelo dto antes, dentro do DTO teria uma função que faria essa conversão.

![image](https://user-images.githubusercontent.com/77133022/216459441-483ca5c8-3d55-4ad2-b5f7-f4637cf79e7f.png)
Aqui nessa parte, depois do `findById()` eu daria um `orElseThrow(NotFoundException::new)` jogando uma exceção, assim vocẽ não precisaria retornar um optional, dessa forma, nem precisaria do .get mais. ( da pra fazer isso em todo lugar que vc da o .get : ) )
Nesses if's de baixo, eu criaria um método dentro da entidade como se fosse um toggle, pode ser um ternário mesmo, caso for false, retorne true, se não retorne true, algo assim.

![image](https://user-images.githubusercontent.com/77133022/216461519-7ff47f8d-5863-427a-946e-faddf6466401.png)
Aqui, você conseguiria utilizar o Stream() e depois o filter para filtrar apenas as motos que são as favoritas, o que acha?

Caso tenha alguma dúvida sobre as sugestões acima, só me pingar lá no discord, beleza? xD

**Comment by BernardoZacaron** [comment]
Obrigado! Apliquei suas sugestões ;)
